# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  displayName: 'Restore dependencies'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'

- task: VSBuild@1
  displayName: 'Build Visual Studio solution'
  inputs:
    solution: '**/*.sln'
    platform: 'Any CPU'
    configuration: 'Release'

- task: VSTest@2
  displayName: 'Run tests'
  inputs:
    platform: 'Any CPU'
    configuration: 'Release'
